---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-myapi-ishtiaq-com-v1-customcrd
  failurePolicy: Fail
  name: mcustomcrd.kb.io
  rules:
  - apiGroups:
    - myapi.ishtiaq.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - customcrds
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-myapi-ishtiaq-com-v1-customcrd
  failurePolicy: Fail
  name: vcustomcrd.kb.io
  rules:
  - apiGroups:
    - myapi.ishtiaq.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - customcrds
  sideEffects: None
