---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - api.ishtiaq.com
  resources:
  - callers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.ishtiaq.com
  resources:
  - callers/finalizers
  verbs:
  - update
- apiGroups:
  - api.ishtiaq.com
  resources:
  - callers/status
  verbs:
  - get
  - patch
  - update
